name: Build APK with EAS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build APK on EAS
        run: eas build -p android --profile preview --non-interactive

      - name: Download APK
        run: |
          BUILD_URL=$(eas build:list --platform=android --limit=1 --json --non-interactive | jq -r '.[0].artifacts.buildUrl')
          wget -O MastiTalk.apk "$BUILD_URL"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MastiTalk-apk
          path: ./frontend/MastiTalk.apk
